<?php

/**
 * @file
 * The Easy Breadcrumb module improves the core system breadcrumb.
 */

use Drupal\Core\Cache\Cache;
use Drupal\easy_breadcrumb\EasyBreadcrumbConstants;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_help().
 */
function easy_breadcrumb_help($route_name) {
  switch ($route_name) {
    case 'help.page.easy_breadcrumb':
      $text = file_get_contents(__DIR__ . "/README.md");

      // If the Markdown module is installed...
      if (\Drupal::moduleHandler()->moduleExists('markdown') === TRUE) {
        // Uses the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        $output = $filter->process($text, 'en');
      }
      // Else the Markdown module is not installed...
      else {
        // Outputs the README in plain text.
        $output = '<pre>' . $text . '</pre>';
      }

      // Adds a link to the Drupal.org documentation pages.
      $output .= t('<p>See the <a href=":documentation">documentation pages</a> on Drupal.org for more information.</p>',
        [
          ':documentation' => 'https://www.drupal.org/docs/contributed-modules/easy-breadcrumb',
        ]);

      return $output;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function easy_breadcrumb_preprocess_block(&$variables) {

  if ($variables['plugin_id'] == 'system_breadcrumb_block') {
    // Get JSON-LD.
    if ($json_ld = \Drupal::service('easy_breadcrumb.structured_data_json_ld')
      ->value()) {

      // Prepare script tag.
      $structured_data = [
        '#tag'        => 'script',
        '#attributes' => ['type' => 'application/ld+json'],
        '#value'      => $json_ld,
      ];

      // Add script tag.
      $variables['#attached']['html_head'][] = [
        $structured_data,
        'easy_breadcrumb_structured_data_json_ld',
      ];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * If the TERM_HIERARCHY configuration option is set, then expire the breadcrumb
 * cache for all child terms.
 */
function easy_breadcrumb_taxonomy_term_update(Term $term) {
  // Returns early if the TERM_HIERARCHY configuration option is not set.
  $config = \Drupal::config('easy_breadcrumb.settings');
  if (!$config->get(EasyBreadcrumbConstants::TERM_HIERARCHY)) {
    return;
  }

  /**
   * @var \Drupal\taxonomy\TermStorageInterface $storage
   */
  $storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $vid = $term->bundle();
  $tree = $storage->loadTree($vid, $term->id());
  $tags = [];

  foreach ($tree as $tree_term) {
    $tags[] = 'easy_breadcrumb:taxonomy_term:' . $tree_term->tid;
  }

  if ($tags) {
    Cache::invalidateTags($tags);
  }
}
