<?php

/**
 * @file
 * Custom theme hooks.
 */

/**
 * Preprocess variables for all templates.
 *
 * @param array $variables
 *   Variables available for preprocess.
 *
 * @phpstan-param array<string, mixed> $variables
 */
function radix_preprocess(array &$variables): void {
  // Inject the current language into every template.
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['language'] ??= $language;

  global $base_url;
  $variables['base_url'] ??= $base_url;

  $variables['path'] ??= \Drupal::service('path.current')->getPath();
}
