<?php

/**
 * @file
 * Utility functions.
 */

/**
 * Cleans identifier to be used in theme suggestions.
 *
 * Unfortunately the core Html::cleanCssIdentifier() method is not doing that
 * well.
 *
 * @param mixed $identifier
 *   The identifier to clean.
 *
 * @return string
 *   The cleaned identifier.
 */
function radix_clean_identifier(mixed $identifier): string {
  // If the identifier is null or not a string, return an empty string.
  if ($identifier === NULL || !is_string($identifier)) {
    return '';
  }

  // Remove any non-alphanumeric characters and replace them with underscores.
  return preg_replace('/[^a-zA-Z0-9_]+/', '_', $identifier);
}
